import { NextResponse } from "next/server";
import crypto from "crypto";
import { supabaseServer } from "@/lib/supabaseServer";

export async function POST(request: Request) {
  try {
    const {
      razorpay_payment_id,
      razorpay_order_id,
      razorpay_signature,
    } = await request.json();

    if (!razorpay_payment_id || !razorpay_order_id || !razorpay_signature) {
      return NextResponse.json(
        { error: "razorpay_payment_id, razorpay_order_id, and razorpay_signature are required" },
        { status: 400 }
      );
    }

    const keySecret = process.env.RAZORPAY_KEY_SECRET;
    if (!keySecret) {
      console.error("Razorpay secret key is missing in env");
      return NextResponse.json(
        { error: "Payment verification credentials are not configured on the server." },
        { status: 500 }
      );
    }

    // 1. Signature Verification
    // Razorpay signature is generated by hashing the razorpay_order_id and razorpay_payment_id joined by a '|' using the secret key.
    const hmac = crypto.createHmac("sha256", keySecret);
    hmac.update(`${razorpay_order_id}|${razorpay_payment_id}`);
    const generatedSignature = hmac.digest("hex");

    const isSignatureValid = generatedSignature === razorpay_signature;

    if (!isSignatureValid) {
      console.error("Razorpay signature verification failed!");
      
      // Attempt to mark order payment as failed
      await supabaseServer
        .from("orders")
        .update({
          payment_status: "failed",
        })
        .eq("razorpay_order_id", razorpay_order_id);

      return NextResponse.json(
        { success: false, error: "Signature verification failed" },
        { status: 400 }
      );
    }

    // 2. Signature is valid: Update order in database to paid and accepted
    const { data: updatedOrder, error: updateError } = await supabaseServer
      .from("orders")
      .update({
        payment_status: "paid",
        status: "accepted", // Order moves to accepted once paid
        razorpay_payment_id,
        razorpay_signature,
      })
      .eq("razorpay_order_id", razorpay_order_id)
      .select()
      .single();

    if (updateError || !updatedOrder) {
      console.error("Error updating order upon payment success:", updateError);
      return NextResponse.json(
        { error: "Payment verified but database update failed" },
        { status: 500 }
      );
    }

    // 3. Return success
    return NextResponse.json({
      success: true,
      order: updatedOrder,
    });

  } catch (error: any) {
    console.error("Razorpay verify-payment route error:", error);
    return NextResponse.json(
      { error: error?.message || "Internal server error during payment verification" },
      { status: 500 }
    );
  }
}
